apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matrix-cubepath-tls
  namespace: matrix-cubepath
spec:
  secretName: matrix-cubepath-tls
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - matrix.stackbp.es
