apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-cubepath-config
  namespace: matrix-cubepath
data:
  API_PORT: "3939"
  DEMO_USER: "demo"
  DEMO_PASSWORD: "demo1234"
  ALLOW_REGISTRATION: "false"
  SECURE_COOKIE: "true"
  APP_URL: "https://matrix.stackbp.es"
  MONITORING_ENABLED: "true"
  MONITORING_K8S_MODE: "in-cluster"
  EMQX_API_URL: "http://emqx-dashboard.apptolast-invernadero-api.svc.cluster.local:18083"
