apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-cubepath-data
  namespace: matrix-cubepath
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
